# This is a basic workflow to help you get started with Actions
name: "Windows Build"

# Controls when the action will run.
on: [push]
  # Triggers the workflow on push or pull request events but only for the master branch
  # push:
  #   branches:
  #     - master
  # pull_request:
  #   branches:
  #     - master
  # release:
  #   types: [published]

  # # Allows you to run this workflow manually from the Actions tab
  # workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
permissions:
  contents: write

jobs:
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest
    strategy:
      matrix:
        dotnet-version: ['8.0.x']
    steps:
      - uses: actions/checkout@v4
      - name: Setup dotnet ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}
      - name: Display dotnet version
        run: dotnet --version
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
      - name: Test
        run: dotnet test
      - name: Publish
        run: dotnet publish CloudSync -r win-x64 -c Release -o Dist
      - name: Zip
        run: Compress-Archive -Destination Dist-${{ github.ref_name }}-win-x64.zip -Path Dist README.md
      - name: Upload
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: Dist-${{ github.ref_name }}-win-x64.zip
